Update packages_reset.yaml

diff --git a/.github/workflows/packages_reset.yaml b/.github/workflows/packages_reset.yaml
--- a/.github/workflows/packages_reset.yaml
+++ b/.github/workflows/packages_reset.yaml
@@ -9,8 +9,6 @@ jobs:
   test:
     runs-on: ubuntu-latest
     steps:
-    
-    
       - name: Free space
         run: |
           df -h
@@ -136,8 +134,26 @@ jobs:
           platforms: ${{ steps.variables.outputs.platform }}
         if: steps.variables.outcome=='success'
 
-      - run: |
-          rclone move js2:/gha-build/$(cat containername)/$(cat arch)/$(cat runstarttime)/binaries/src/contrib js2:/container-binaries/$(cat containername)/$(cat arch)/binaries/src/contrib -vvvvvv
+
+      - name: Install rclone & add rclone conf file
+        uses: nick-fields/retry@v2
+        env:
+            RCLONE_CONF: ${{secrets.RCLONE_CONF}}
+        with:
+          timeout_minutes: 20
+          max_attempts: 10
+          shell: bash
+          command: |
+            set -xe
+            sudo -v ; curl https://rclone.org/install.sh | sudo bash || true
+            echo "$RCLONE_CONF" > ~/.rclone.conf
+            if ! command -v rclone &> /dev/null
+            then
+                echo "rclone could not be found"
+                exit 1;
+            fi
+            mkdir -p /tmp/image
+            rclone move js2:/gha-build/$(cat containername)/$(cat arch)/$(cat runstarttime)/binaries/src/contrib js2:/container-binaries/$(cat containername)/$(cat arch)/binaries/src/contrib -vvvvvv
         if: steps.variables.outcome=='success'
 
   packages-build:
