K8s add

diff --git a/.github/workflows/write_PACKAGES.yaml b/.github/workflows/write_PACKAGES.yaml
--- a/.github/workflows/write_PACKAGES.yaml
+++ b/.github/workflows/write_PACKAGES.yaml
@@ -12,30 +12,32 @@ jobs:
       - uses: actions/setup-python@v4
         with:
           python-version: '3.10' 
-      - name: Add rclone conf file and PEM key for ssh
+
+      - name: Start a local k8s cluster
+        uses: jupyterhub/action-k3s-helm@v3
+        with:
+          k3s-channel: latest
+
+      - name: Verify function of k8s, kubectl, and helm
         run: |
-          echo "$RCLONE_CONF" > ~/.rclone.conf
-          echo "$VMKEY" > ~/packages.pem
-          echo "$CLOUDBRIDGE_CONF" > ~/.cloudbridge
-          chmod 400 ~/packages.pem
+          kubectl version
+          helm version
+          helm repo add wunderio https://storage.googleapis.com/charts.wdr.io
+          echo "$RCLONE_CSI_SECRET" > rclone-secret.yaml
+          kubectl create ns rclone
+          sed -i "s#HOLDERPATH#gha-build/$(cat containername)/$(cat arch)/$(cat runstarttime)/binaries#g" rclone-secret.yaml
+          kubectl -n rclone apply -f rclone-secret.yaml
+          helm upgrade --install --create-namespace -n rclone wunderio/csi-rclone --wait
+          kubectl -n rclone apply -f .github/scripts/k8s/k8s-resources.yaml
+          while [[ $(kubectl get pods package-file -c sleep -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; do
+            sleep 1
+          done
+          mkdir -p /tmp
+          kubectl cp -c sleep -n rclone package-file:/mnt/results/PACKAGES.gz /tmp/PACKAGES.gz
+          kubectl cp -c sleep -n rclone package-file:/mnt/results/PACKAGES.rds /tmp/PACKAGES.rds
+          kubectl cp -c sleep -n rclone package-file:/mnt/results/PACKAGES /tmp/PACKAGES
         env:
-          CLOUDBRIDGE_CONF: ${{secrets.CLOUDBRIDGE_CONF}}
-          RCLONE_CONF: ${{secrets.RCLONE_CONF}}
-          VMKEY: ${{secrets.VMKEY}}
-
-      - name: Launch instance in cloudbridge
-        shell: bash
-        run: |
-          set -x
-          # Install cloudbridge
-          mkdir -p /tmp/binaries
-          python -m pip install 'cloudbridge[openstack] @ git+https://github.com/cloudve/cloudbridge@main'
-          # Launch js2 instance
-          python .github/scripts/instlaunch.py -n 1 -m Featured-Ubuntu22 -l gha-build -s 0 -t m3.medium -p openstack --network 739b1ee6-1e81-497f-8f76-188e17965d0e --subnet d58af0f2-1f4b-48cc-b54b-c4b3b59cc988 --firewall f93c379a-00e2-4cb4-8e6a-9ac3de8361b4 --router 7392886e-5751-41c0-b298-7f86f757dd7e --volume-size 300
-
-      - name: Install ansible
-        run: |
-          python -m pip install ansible
+          RCLONE_CSI_SECRET: ${{secrets.RCLONE_CSI_SECRET}}
 
       - name: Install rclone & add rclone conf file
         uses: nick-fields/retry@v2
@@ -43,30 +45,19 @@ jobs:
             RCLONE_CONF: ${{secrets.RCLONE_CONF}}
         with:
           timeout_minutes: 20
-          max_attempts: 3
-          shell: bash
-          command: |
-            echo "$RCLONE_CONF" > ~/.rclone.conf
-            set -x
-            mkdir -p /tmp/binaries
-            grep -roh "^.*tar.gz$" lists > /tmp/tarlist
-            ls /tmp/binaries/ > /tmp/curtars
-            comm -2 -3 <(sort /tmp/tarlist) <(sort /tmp/curtars) > /tmp/missingtars
-            mkdir -p .github/scripts/ansible/files
-            split -l 200 /tmp/missingtars .github/scripts/ansible/files/tars
-
-      - name: Run ansible playbook to create PACKAGES file in VM
-        run: |
-          VMIP=$(python -c 'from cloudbridge.factory import CloudProviderFactory, ProviderList; prov = CloudProviderFactory().create_provider("openstack", {}); inst = prov.compute.instances.find(label="gha-build-inst-0")[0]; inst.wait_till_ready(); print(inst.public_ips[0])')
-          sed -i "s@##IP##@$VMIP@g" .github/scripts/ansible/inventory
-          sed -i "s@##PEM##@$(realpath ~/packages.pem)@g" .github/scripts/ansible/inventory
-          ansible-playbook -vvv -T60 .github/scripts/ansible/ansible-packages.yaml -i .github/scripts/ansible/inventory --extra-vars "container_base_image=ghcr.io/almahmoud/gha-build-anvil-jupyter-amd64:linux-amd64"
-
-      - name: Delete VM
-        uses: nick-fields/retry@v2
-        with:
-          timeout_minutes: 10
           max_attempts: 10
           shell: bash
           command: |
-            python .github/scripts/instlaunch.py --delete "$(python -c 'from cloudbridge.factory import CloudProviderFactory, ProviderList; prov = CloudProviderFactory().create_provider("openstack", {}); inst = prov.compute.instances.find(label="gha-build-inst-0")[0]; print(inst.id)')"
+            set -xe
+            sudo -v ; curl https://rclone.org/install.sh | sudo bash || true
+            echo "$RCLONE_CONF" > ~/.rclone.conf
+            if ! command -v rclone &> /dev/null
+            then
+                echo "rclone could not be found"
+                exit 1;
+            fi
+
+      - run: |
+          rclone copyto /tmp/PACKAGES js2:/gha-build/$(cat containername)/$(cat arch)/$(cat runstarttime)/PACKAGES -vvvvv
+          rclone copyto /tmp/PACKAGES.gz js2:/gha-build/$(cat containername)/$(cat arch)/$(cat runstarttime)/PACKAGES.gz -vvvvv
+          rclone copyto /tmp/PACKAGES.rds js2:/gha-build/$(cat containername)/$(cat arch)/$(cat runstarttime)/PACKAGES.rds -vvvvv
